[package]
name = "rv_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
rv_server = { path = "../rv_server" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
